config/routes.rb
# frozen_string_literal: true

Grandham::Application.routes.draw do # rubocop:disable Metrics/BlockLength
  get "qr_generator/image"

  get "error/access_denied"

  devise_for :users

  resources :publishers
  resources :libraries
  resources :authors
  resources :books do
    post :update_cover, on: :member
  end

  resource :search do
    get :books, on: :member
    get :authors, on: :member
    get :publishers, on: :member
    get :libraries, on: :member
  end

  root to: "books#index"

  resources :language do
    namespace :publisher do
      resources :books
    end

    namespace :library do
      resources :books
    end

    namespace :admin do
      resources :publishers
      resources :authors
      resources :libraries
      resources :dashboard
      resources :books do
        post :publish, on: :member
        post :unpublish, on: :member
      end

      resources :new_items do
        post :approve, on: :member
        post :discard, on: :member
      end

      resources :edits do
        post :approve, on: :member
        post :discard, on: :member
        post :replace, on: :member
      end
    end

    resources :authors, :publishers, :libraries
    resources :books do
      get :history, on: :member
    end

    resources :authors do
      get :books, on: :member
    end

    resources :publishers do
      get :books, on: :member
    end

    resources :libraries do
      get :books, on: :member
    end
  end
  namespace :api do
    namespace :v1 do
      resources :books, only: %i[show index]
      resources :authors, only: %i[show index]
      resources :libraries, only: %i[show index]
      resources :publishers, only: %i[show index]
    end
  end
end

app/models/edit.rb
# frozen_string_literal: true

class Edit < ApplicationRecord
  belongs_to :editable, polymorphic: true
  belongs_to :language

  scope :not_reviewed, -> { where(state: "open") }
  scope :approved, -> { where(state: "approved") }

  belongs_to :book
  belongs_to :user
end

app/controllers/admin/edits_controller.rb
# frozen_string_literal: true

class Admin::EditsController < AdminController
  load_and_authorize_resource :edit

  before_action :find_edit, except: [:index]

  def index
    @edits = current_language.edits.not_reviewed
  end

  def approve
    object = @edit.editable

    object.update_attribute(@edit.field, @edit.new_value)
    @edit.update state: "approved", reviewed_by_user_id: current_user.id

    path = if current_language.edits.not_reviewed.empty?
             language_admin_dashboard_index_path(current_language)
           else
             language_admin_edits_path(current_language)
           end

    redirect_to path
  end

  def discard
    @edit.update state: "discarded", reviewed_by_user_id: current_user.id

    path = if current_language.edits.not_reviewed.empty?
             language_admin_dashboard_index_path(current_language)
           else
             language_admin_edits_path(current_language)
           end

    redirect_to path
  end

  def replace
    old_object = @edit.editable
    old_object_class = old_object.class
    objects_collection = @edit.editable_type.downcase.pluralize

    @edit.book.send(objects_collection).delete(old_object)
    @edit.book.send(objects_collection) << old_object_class.where(name: @edit.new_value, language_id: @edit.book.language.id).first_or_create!

    @edit.update state: "replaced", reviewed_by_user_id: current_user.id

    redirect_to language_admin_edits_path(current_language)
  end

  private

  def find_edit
    @edit = current_language.edits.find(params[:id])
  end
end

app/helpers/edit_helper.rb
# frozen_string_literal: true

module EditHelper
  def record_edit(object, object_params, book_id = nil)
    object_params.keys.each do |field|
      # Safeguarding the following .send call.

      next unless object.class.new.attributes.key?(field)

      old_value = object.send(field)
      new_value = object_params[field]

      next if old_value.to_s == new_value.to_s

      if current_user.admin?
        object.update object_params
        state = "approved"
      else
        flash[:notice] = "Your edit(s) have been submitted for approval."
        state = "open"
      end

      object.edits.create old_value: old_value, new_value: new_value, user_id: current_user.id,
                          field: field, language_id: object.language.id, book_id: book_id,
                          state: state
    end
  end

  def author_path(object, param = nil)
    book_path = current_book ? "?book_id=#{current_book.grandham_id}" : ""
    super(object, param) + book_path
  end

  def publisher_path(object, param = nil)
    book_path = current_book ? "?book_id=#{current_book.grandham_id}" : ""
    super(object, param) + book_path
  end

  def library_path(object, param = nil)
    book_path = current_book ? "?book_id=#{current_book.grandham_id}" : ""
    super(object, param) + book_path
  end
end

app/views/admin/edits/_edit.html.haml
.edit-item
  %p{style: 'display: inline;'}
    %i.icon-user
    = edit.user.login

  .pull-right
    %i.icon-time
      = edit.created_at.strftime('%e %b %Y %I:%M %p')

    - if defined? show_perma_link
      |
      = link_to 'permalink', language_admin_edit_path(language_id: current_language, id: edit)

  - if Book.associated_records.include?(edit.editable_type) && edit.book_id

    %p
      .row
        %code.col-md-2.edit-attribute Edited in book
        .col-md-8
          = link_to edit.book.grandham_id, language_book_path(edit.book.language, edit.book), target: '_blank'

  %p
    .row
      %code.col-md-2.edit-attribute= edit.editable_type
      .col-md-8
        = link_to edit.editable.name, send("language_#{edit.editable_type.downcase}_path", edit.editable.language, edit.editable), target: '_blank'
  %p
    .row
      %code.col-md-2.edit-attribute= "#{edit.field.capitalize} (old)"
      .col-md-8
        = edit.old_value

  %p
    .row
      %code.col-md-2.edit-attribute= "#{edit.field.capitalize} (new)"
      .col-md-8
        = edit.new_value

  %br

  - if Book.associated_records.include?(edit.editable_type) && edit.book_id
    = link_to "Save #{edit.editable_type.downcase}", approve_language_admin_edit_path(language_id: current_language, id: edit), class: 'btn btn-small btn-success', method: :post

    = link_to "Replace #{edit.editable_type.downcase} in book", replace_language_admin_edit_path(language_id: current_language, id: edit), class: 'btn btn-small btn-success', method: :post
  - else
    = link_to 'Approve', approve_language_admin_edit_path(language_id: current_language, id: edit), class: 'btn btn-small btn-success', method: :post

  = link_to 'Discard', discard_language_admin_edit_path(language_id: current_language, id: edit), class: 'btn btn-small btn-primary', method: :post

app/views/admin/edits/index.html.haml
.container
  .row
    .span12.inline
      .pull-right
        %p= I18n.t('edit.pending', count: @edits.count)
      .pull-left
        %h3= I18n.t('edit.edits')
  .row
    .span12
      - @edits.each do |edit|
        = render partial: 'edit', locals: { edit: edit, show_perma_link: true }

app/views/admin/edits/show.html.haml
.container
  .row
    .span12.inline
      %h3= "Edit ##{@edit.id}"
  .row
    .span12
      = render partial: 'edit', locals: { edit: @edit }