config/routes.rb
# frozen_string_literal: true

Grandham::Application.routes.draw do # rubocop:disable Metrics/BlockLength
  get "qr_generator/image"

  get "error/access_denied"

  devise_for :users

  resources :publishers
  resources :libraries
  resources :authors
  resources :books do
    post :update_cover, on: :member
  end

  resource :search do
    get :books, on: :member
    get :authors, on: :member
    get :publishers, on: :member
    get :libraries, on: :member
  end

  root to: "books#index"

  resources :language do
    namespace :publisher do
      resources :books
    end

    namespace :library do
      resources :books
    end

    namespace :admin do
      resources :publishers
      resources :authors
      resources :libraries
      resources :dashboard
      resources :books do
        post :publish, on: :member
        post :unpublish, on: :member
      end

      resources :new_items do
        post :approve, on: :member
        post :discard, on: :member
      end

      resources :edits do
        post :approve, on: :member
        post :discard, on: :member
        post :replace, on: :member
      end
    end

    resources :authors, :publishers, :libraries
    resources :books do
      get :history, on: :member
    end

    resources :authors do
      get :books, on: :member
    end

    resources :publishers do
      get :books, on: :member
    end

    resources :libraries do
      get :books, on: :member
    end
  end
  namespace :api do
    namespace :v1 do
      resources :books, only: %i[show index]
      resources :authors, only: %i[show index]
      resources :libraries, only: %i[show index]
      resources :publishers, only: %i[show index]
    end
  end
end

app/controllers/admin/dashboard_controller.rb
# frozen_string_literal: true

class Admin::DashboardController < AdminController
  authorize_resource class: false

  def index; end
end

app/helpers/admin/dashboard_helper.rb
# frozen_string_literal: true

module Admin::DashboardHelper
end

app/views/admin/dashboard/index.html.haml
.container
  %br
  .row
    .col-md-4.offset1
      .admin-widget
        .caption
          %h3 New
        .value
          %p= link_to current_language.new_items.not_reviewed.count, language_admin_new_items_path(current_language)

    .col-md-4.offset2
      .admin-widget
        .caption
          %h3 Edits
        .value
          %p= link_to current_language.edits.not_reviewed.count, language_admin_edits_path(current_language)

  %br
  .row
    .col-md-10.offset1
      .admin-widget.large
        .caption
          %h3 Status
        .status
          .row
            .col-md-2
              %h4= link_to 'Books', language_admin_books_path(current_language)
            .col-md-3
              %h4= current_language.books.count
          .row
            .col-md-2
              %h4= link_to 'Authors', language_admin_authors_path(current_language)
            .col-md-3
              %h4= current_language.authors.count
          .row
            .col-md-2
              %h4= link_to 'Publishers', language_admin_publishers_path(current_language)
            .col-md-3
              %h4= current_language.publishers.count
          .row
            .col-md-2
              %h4= link_to 'Libraries', language_admin_libraries_path(current_language)
            .col-md-3
              %h4= current_language.libraries.count