config/routes.rb
# frozen_string_literal: true

Grandham::Application.routes.draw do # rubocop:disable Metrics/BlockLength
  get "qr_generator/image"

  get "error/access_denied"

  devise_for :users

  resources :publishers
  resources :libraries
  resources :authors
  resources :books do
    post :update_cover, on: :member
  end

  resource :search do
    get :books, on: :member
    get :authors, on: :member
    get :publishers, on: :member
    get :libraries, on: :member
  end

  root to: "books#index"

  resources :language do
    namespace :publisher do
      resources :books
    end

    namespace :library do
      resources :books
    end

    namespace :admin do
      resources :publishers
      resources :authors
      resources :libraries
      resources :dashboard
      resources :books do
        post :publish, on: :member
        post :unpublish, on: :member
      end

      resources :new_items do
        post :approve, on: :member
        post :discard, on: :member
      end

      resources :edits do
        post :approve, on: :member
        post :discard, on: :member
        post :replace, on: :member
      end
    end

    resources :authors, :publishers, :libraries
    resources :books do
      get :history, on: :member
    end

    resources :authors do
      get :books, on: :member
    end

    resources :publishers do
      get :books, on: :member
    end

    resources :libraries do
      get :books, on: :member
    end
  end
  namespace :api do
    namespace :v1 do
      resources :books, only: %i[show index]
      resources :authors, only: %i[show index]
      resources :libraries, only: %i[show index]
      resources :publishers, only: %i[show index]
    end
  end
end

app/models/publisher.rb
# frozen_string_literal: true

class Publisher < ApplicationRecord
  belongs_to :language, optional: true

  validates :name, presence: true

  has_many :publications, dependent: :destroy
  has_many :books, through: :publications

  has_many :edits, as: :editable, dependent: :destroy

  has_many :logos, as: :imageable, dependent: :destroy
  accepts_nested_attributes_for :logos

  before_create :set_grandham_id
  after_create :set_default_logo

  searchkick word: [:name]

  def to_param
    grandham_id
  end

  private

  def set_default_logo
    logos.create if logos.empty?
  end

  def set_grandham_id
    self.grandham_id = SecureRandom.hex(4)
  end
end

app/controllers/admin/publishers_controller.rb
# frozen_string_literal: true

class Admin::PublishersController < AdminController
  load_and_authorize_resource :publisher, find_by: :grandham_id

  respond_to :html

  before_action :find_publisher, except: %i[index new]

  def index
    @publishers = current_language.publishers

    respond_with @publishers
  end

  def edit; end

  def new
    @publisher = current_language.publishers.new
  end

  def create
    @publisher = current_language.publishers.new(publisher_params)

    if @publisher.save
      redirect_to language_admin_publishers_path(current_language), notice: "Publisher was successfully created."
    else
      render action: "new"
    end
  end

  def update
    if @publisher.update(publisher_params)
      redirect_to language_admin_publishers_path(current_language), notice: "Publisher was successfully updated."
    else
      render action: "edit"
    end
  end

  private

  def publisher_params
    params.require(:publisher).permit(:name, :created_at, :updated_at, :language_id, :grandham_id, :place)
  end

  def find_publisher
    @publisher = current_language.publishers.find_by(grandham_id: params[:id])
  end
end

app/controllers/api/v1/publishers_controller.rb
# frozen_string_literal: true

class Api::V1::PublishersController < ApiBaseController
  before_action :set_publisher, only: :show
  before_action :parse_json_api_params

  def show
    render json: PublisherSerializer.new(@publisher)
  end

  def index
    @publishers = if @query.search_query.present?
                    Publisher.search(@query.search_query, page: @query.page_number, per_page: @query.per_page)
                  else
                    Publisher.paginate(page: @query.page_number, per_page: @query.per_page)
                  end

    render json: PublisherSerializer.new(@publishers)
  end

  private

  def set_publisher
    @publisher = Publisher.find_by!(grandham_id: params[:id])
  end
end

app/controllers/publisher/books_controller.rb
# frozen_string_literal: true

class Publisher::BooksController < PublisherController
  load_and_authorize_resource :book, find_by: :grandham_id

  def new
    @book = Book.unscoped.new
    @book.authors.build
    @book.publishers.build
    @book.covers.build
    @book.libraries.build
  end

  def create
    @book = Book.unscoped.new(book_params)

    @book.publishers << current_user.publisher

    if @book.save
      @book.new_items.create user_id: current_user.id, language_id: @book.language.id, state: "approved"
      @book.approve!

      redirect_to language_book_path(@book.language, @book)
    else
      @book.covers.build
      render "new"
    end
  end

  private

  def book_params
    params.require(:book).permit(:grandham_id, :language_id, :title, :isbn, :pages, :year,
                                 :description, :edition, :ddc, :volume, :series, :price,
                                 :length, :title_orginal, :illustrator, :note, :preface,
                                 :created_at, :updated_at, :approved, :published)
  end
end

app/controllers/publisher_controller.rb
# frozen_string_literal: true

class PublisherController < ApplicationController
end

app/controllers/publishers_controller.rb
# frozen_string_literal: true

class PublishersController < ApplicationController
  load_and_authorize_resource :publisher, find_by: :grandham_id

  respond_to :html, :json

  before_action :find_publisher, only: %i[show update]

  def index
    collection = (current_language&.publishers) || Publisher

    @publishers = collection.paginate(page: params[:page], per_page: 10)

    respond_with @publishers
  end

  def show
    @publisher = Publisher.find_by(grandham_id: params[:id])

    respond_with @publisher
  end

  def update
    respond_to do |format|
      book_id = (book = Book.find_by(grandham_id: params[:book_id])) ? book.id : nil
      record_edit @publisher, params[:publisher], book_id

      format.html { redirect_to language_publisher_path(@publisher.language, @publisher) }
      format.json { respond_with_bip(@publisher) }
    end
  end

  def books
    @books = @publisher.books.paginate(page: params[:page], per_page: 20)
  end

  private

  def find_publisher
    @publisher = Publisher.find_by(grandham_id: params[:id])
  end
end

app/helpers/admin/publishers_helper.rb
# frozen_string_literal: true

module Admin::PublishersHelper
end

app/helpers/publisher/books_helper.rb
# frozen_string_literal: true

module Publisher::BooksHelper
end

app/helpers/publishers_helper.rb
# frozen_string_literal: true

module PublishersHelper
  def publisher_logo(publisher)
    if publisher.logos.empty?
      "/book_cover_missing.png"
    else
      publisher.logos.last.image.url(:thumb)
    end
  end
end

app/views/admin/publishers/_form.html.haml
- form_path = @publisher.new_record? ? language_admin_publishers_path : language_admin_publisher_path
= simple_form_for @publisher, url: form_path, html: { class: 'form-horizontal' } do |f|
  %fieldset
    %legend= @publisher.new_record? ? 'Add Publisher' : 'Edit publisher'

    = f.input :name, as: :string, input_html: { class: 'input-xxlarge' }
    = f.input :place, as: :string, input_html: { class: 'input-xxlarge' }

    = f.fields_for :logos do |logo_form|
      .control-group
        = logo_form.label :image, 'Logo', class: 'control-label'
        .controls
          = logo_form.file_field :image

      .form-actions
        = f.submit 'Submit', class: 'btn btn-primary'
        = link_to 'Cancel', language_admin_publishers_path(current_language), class: 'btn'

app/views/admin/publishers/edit.html.haml
.container
  .row
    .span8.offset1
      = render 'form'

app/views/admin/publishers/index.html.haml
.container
  .row
    .span8
      %h3= I18n.t('publisher.publishers')
    .span4
      .pull-right
        = link_to 'Add', new_language_admin_publisher_path(current_language), class: 'btn btn-primary'

  .row
    .span12
      %table.table.table-striped.grandham-list-data-table
        %thead
          %th Name
          %th Place
          %th
        %tbody.grandham-list
          - @publishers.each do |publisher|
            %tr
              %td.tex-item
                = link_to publisher.name, language_publisher_path(publisher.language, publisher)
              %td.tex-item
                = publisher.place
              %td.tex-item
                = link_to 'edit', edit_language_admin_publisher_path(current_language, publisher)

app/views/admin/publishers/new.html.haml
.container
  .row
    .span8.offset1
      = render 'form'