config/routes.rb
# frozen_string_literal: true

Grandham::Application.routes.draw do # rubocop:disable Metrics/BlockLength
  get "qr_generator/image"

  get "error/access_denied"

  devise_for :users

  resources :publishers
  resources :libraries
  resources :authors
  resources :books do
    post :update_cover, on: :member
  end

  resource :search do
    get :books, on: :member
    get :authors, on: :member
    get :publishers, on: :member
    get :libraries, on: :member
  end

  root to: "books#index"

  resources :language do
    namespace :publisher do
      resources :books
    end

    namespace :library do
      resources :books
    end

    namespace :admin do
      resources :publishers
      resources :authors
      resources :libraries
      resources :dashboard
      resources :books do
        post :publish, on: :member
        post :unpublish, on: :member
      end

      resources :new_items do
        post :approve, on: :member
        post :discard, on: :member
      end

      resources :edits do
        post :approve, on: :member
        post :discard, on: :member
        post :replace, on: :member
      end
    end

    resources :authors, :publishers, :libraries
    resources :books do
      get :history, on: :member
    end

    resources :authors do
      get :books, on: :member
    end

    resources :publishers do
      get :books, on: :member
    end

    resources :libraries do
      get :books, on: :member
    end
  end
  namespace :api do
    namespace :v1 do
      resources :books, only: %i[show index]
      resources :authors, only: %i[show index]
      resources :libraries, only: %i[show index]
      resources :publishers, only: %i[show index]
    end
  end
end

app/models/search.rb
# frozen_string_literal: true

class Search
  attr_reader :query, :resource, :page

  def initialize(resource, query, page)
    @query    = query
    @resource = resource
    @page = page
  end

  def results
    resource.search(query, page: page, per_page: 20)
  end
end

app/controllers/searches_controller.rb
# frozen_string_literal: true

class SearchesController < ApplicationController
  before_action :get_results

  def books; end

  def authors; end

  def publishers; end

  def libraries; end

  private

  def resource(action)
    resources = %w[books authors libraries publishers]

    if resources.include?(action)
      action.camelcase.singularize.constantize
    else
      redirect_to error_access_denied_path
    end
  end

  def get_results
    search_query = MalayalamTextNormalizer.new(params[:query]).call
    @results = Search.new(resource(params[:action]), search_query, params[:page]).results if params[:query].present?
  end
end

app/helpers/searches_helper.rb
# frozen_string_literal: true

module SearchesHelper
end

app/views/searches/_search_nav_links.html.haml
.col-md-12
  %ul.nav.nav-tabs
    %li{ class: is_active(activated_page, 'books') }
      = link_to 'Books', books_search_path
    %li{ class: is_active(activated_page, 'authors') }
      = link_to 'Authors', authors_search_path
    %li{ class: is_active(activated_page, 'publishers') }
      = link_to 'Publishers', publishers_search_path
    %li{ class: is_active(activated_page, 'libraries') }
      = link_to 'Libraries', libraries_search_path

app/views/searches/authors.html.haml
.row
  = render partial: 'search_nav_links', locals: { activated_page: :authors }

%br
.container
  .row
    .col-md-8.col-offset-1
      %form{ action: authors_search_path, method: 'get' }
        .form-group
          %input{ name: 'query', value: params[:query], class: 'input-xxlarge search-field', placeholder: 'Search authors' }
          %button.btn-success{ type: 'submit', class: 'btn btn-primary' }
            %span.glyphicon-search.glyphicon
            = I18n.t('.search')
      %br
      - if @results && @results.any?
        = render @results
        = will_paginate @results, renderer: BootstrapPagination::Rails

app/views/searches/books.html.haml
.row
  = render partial: 'search_nav_links', locals: { activated_page: :books }

%br
.container
  .row
    .col-md-8.col-offset-1
      %form{ action: books_search_path, method: 'get' }
        .form-group
          %input{ name: 'query', value: params[:query], class: 'input-xxlarge search-field', placeholder: 'Search books' }
          %button.btn-success{ type: 'submit', class: 'btn btn-primary' }
            %span.glyphicon-search.glyphicon
            = I18n.t('.search')
      %br
      - if @results && @results.any?
        = render @results
        = will_paginate @results, renderer: BootstrapPagination::Rails

app/views/searches/libraries.html.haml
.row
  = render partial: 'search_nav_links', locals: { activated_page: :libraries }

%br
.container
  .row
    .col-md-8.col-offset-1
      %form{ action: libraries_search_path, method: 'get' }
        .form-group
          %input{ name: 'query', value: params[:query], class: 'input-xxlarge search-field', placeholder: 'Search libraries' }
          %button.btn-success{ type: 'submit', class: 'btn btn-primary' }
            %span.glyphicon-search.glyphicon
            = I18n.t('.search')
      %br
      - if @results && @results.any?
        = render @results
        = will_paginate @results, renderer: BootstrapPagination::Rails

app/views/searches/publishers.html.haml
.row
  = render partial: 'search_nav_links', locals: { activated_page: :publishers }

%br
.container
  .row
    .col-md-8.col-offset-1
      %form{ action: publishers_search_path, method: 'get' }
        .form-group
          %input{ name: 'query', value: params[:query], class: 'input-xxlarge search-field', placeholder: 'Search publishers' }
          %button.btn-success{ type: 'submit', class: 'btn btn-primary' }
            %span.glyphicon-search.glyphicon
            = I18n.t('.search')
      %br
      - if @results && @results.any?
        = render @results
        = will_paginate @results, renderer: BootstrapPagination::Rails